sudo: false

language: rust
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - nightly
  - 1.31
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"
cache: cargo

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add clippy; fi

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo fmt -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo clippy -- -D clippy::all; fi
  - cargo test --all -- --nocapture
  # Validate benches still work.
  - cargo bench --all -- --test
  # Because failpoints inject failure in code path, which will affect all concurrently running tests, Hence they need to be synchronized, which make tests slow.
  - cargo test --tests --features failpoint -- --nocapture