language: rust
sudo: false
env:
  global:
    - RUST_BACKTRACE=1
cache: cargo

# `allow_failures` requires this, but we set it below.
rust:

matrix:
  include:
  - rust: stable
  - rust: nightly
    install: rm -f ~/.cargo/bin/cargo-clippy && cargo install -f clippy || true

script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which cargo-clippy && cargo clippy
  - cargo test --all -- --nocapture
