[package]
name = "raft"
version = "0.5.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["raft", "distributed-systems", "ha"]
repository = "https://github.com/pingcap/raft-rs"
readme = "README.md"
homepage = "https://github.com/pingcap/raft-rs"
documentation = "https://docs.rs/raft"
description = "The rust language implementation of Raft algorithm."
categories = ["algorithms", "database-implementations"]
edition = "2018"

[workspace]
members = ["proto"]

[features]
default = []
# Enable failpoints
failpoint = ["fail"]

# Make sure to synchronize updates with Harness.
[dependencies]
log = "0.4.6"
protobuf = "2.7.0"
lazy_static = "1.3.0"
prost = "0.5.0"
prost-derive = "0.5.0"
bytes = "0.4.12"
slog = "2.4.1"
quick-error = "1.2.2"
raft-proto = { path = "proto" }
rand = "0.7.0"
hashbrown = "0.5.0"
fail = { version = "0.2.1", optional = true }
getset = "0.0.7"
slog-stdlog = "3.0.2"
slog-term = "2.4.0"
slog-envlogger = "2.1.0"

[dev-dependencies]
criterion = "0.2.11"
lazy_static = "1.3.0"
harness = { path = "harness" }
regex = "1.1.7"
slog-async = "2.3.0"

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "pingcap/raft-rs" }

[[example]]
name = "single_mem_node"
path = "examples/single_mem_node/main.rs"

[[example]]
name = "five_mem_node"
path = "examples/five_mem_node/main.rs"
