[package]
name = "datadriven"
version = "0.1.0"
authors = ["accelsao <bebe8277@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
difflib = "0.4.0"
scanner-rust = "2.0.12"
regex = "1.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
log = "0.4.11"
pretty_assertions = "0.6.1"
nom = "6.0.0-alpha1"